version: '3.1'
services:
    db:
        image: postgres:10.8-alpine
        container_name: db
        ports:
            - "54320:5432"
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - ./docker/postgres/sql:/docker-entrypoint-initdb.d
    server:
        build:
            context: .
            dockerfile: Dockerfile-server
        container_name: server
        volumes:
            - .:/src
        depends_on:
            - db
        ports:
            - "3000:3000"
        expose:
            - "3000"
    client:
        build:
            context: .
            dockerfile: Dockerfile-client
        container_name: client
        volumes:
            - .:/src
        depends_on:
            - server
        ports:
            - "8080:8080"
        expose:
            - "8080"
